In [46]:
import torch
import torch.nn.functional as F
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
from rac.pred_models import CustomTensorDataset, ACCNet
import numpy as np

In [47]:
transform = transforms.Compose([
            transforms.RandomCrop(32, padding=4),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
        ])

batch_size = 256

trainset = torchvision.datasets.CIFAR10(root='../datasets/cifar10_original_data', train=True,
                                        download=True, transform=transform)
#trainset.data = trainset.data
#trainset.targets = trainset.targets
X_train = trainset.data
y_train = trainset.targets
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=8)

testset = torchvision.datasets.CIFAR10(root='../datasets/cifar10_original_data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=1024, num_workers=8)

X_test = testset.data
y_test = testset.targets

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

    

Files already downloaded and verified
Files already downloaded and verified


In [48]:
def clustering_from_clustering_solution(clustering_solution):
    num_clusters = np.max(clustering_solution) + 1
    clustering = [[] for _ in range(num_clusters)]
    for i in range(len(clustering_solution)):
        clustering[clustering_solution[i]].append(i)
    return clustering, num_clusters

def sim_matrix_from_clustering(clustering, N):
    pairwise_similarities = -np.ones((N, N))
    for cind in clustering:
        pairwise_similarities[np.ix_(cind, cind)] = 1
    return pairwise_similarities

In [49]:
train_sol = clustering_from_clustering_solution(y_train[:10000])
train_sim_matrix = sim_matrix_from_clustering(train_sol[0], len(y_train[:10000]))

test_sol = clustering_from_clustering_solution(y_test[:10000])
test_sim_matrix = sim_matrix_from_clustering(test_sol[0], len(y_test[:10000]))

In [50]:
train_sim_matrix.shape

(10000, 10000)

In [51]:
def get_pairs(prop_pos, prop_neg, sim_matrix, data):
    N = sim_matrix.shape[0]
    lower_triangle_indices = np.tril_indices(N, -1)
    ind_pos = np.where(sim_matrix[lower_triangle_indices] == 1)[0]
    ind_neg = np.where(sim_matrix[lower_triangle_indices] == -1)[0]
    num_pos = int(len(ind_pos)*prop_pos)
    num_neg = int(len(ind_neg)*prop_neg)
    print("num_pos: ", num_pos)
    print("num_neg: ", num_neg)
    ind_pos = np.random.choice(ind_pos, num_pos)
    ind_neg = np.random.choice(ind_neg, num_neg)
    if num_pos < num_neg:
        indices = np.concatenate([ind_neg, ind_pos])
    else:
        indices = np.concatenate([ind_pos, ind_neg])
    ind1, ind2 = lower_triangle_indices[0][indices], lower_triangle_indices[1][indices]
    x1 = data[ind1]
    x2 = data[ind2]
    y = sim_matrix[ind1, ind2]
    lab1 = np.where(y >= 0)
    lab2 = np.where(y < 0)
    y[lab1] = 1.0
    y[lab2] = 0.0
    return x1, x2, y

In [52]:
x1_train, x2_train, y_train_pairs = get_pairs(0.001, 0.0001, train_sim_matrix, X_train)
x1_test, x2_test, y_test_pairs = get_pairs(0.001, 0.0001, test_sim_matrix, X_test)

num_pos:  4998
num_neg:  4499
num_pos:  4995
num_neg:  4500


In [53]:
cifar_training_transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
])

cifar_test_transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
])

train_dataset = CustomTensorDataset(x1_train, x2_train, y_train_pairs, train=True, transform=cifar_training_transform)
test_dataset = CustomTensorDataset(x1_test, x2_test, y_test_pairs, transform=cifar_test_transform)  

In [54]:
batch_size = 128
#class_sample_count = [10, 1, 20, 3, 4] # dataset has 10 class-1 samples, 1 class-2 samples, etc.
class_sample_count = np.unique(y_train_pairs, return_counts=True)[1].tolist()
#print(class_sample_count)
weights = 1/torch.Tensor(class_sample_count)
weights = weights[y_train_pairs]
#print(weights)
sampler = torch.utils.data.sampler.WeightedRandomSampler(weights=weights, num_samples=len(weights), replacement=True)
#train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, sampler=sampler)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=128, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, shuffle=False, batch_size=1024)
#trainloader = data_utils.DataLoader(train_dataset, batch_size = batch_size, shuffle=True, sampler = sampler)

In [24]:
#for x1, x2, y in train_loader:
    #print(np.unique(y, return_counts=True))

In [55]:
len(train_dataset)

9996

In [26]:
criterion = nn.BCEWithLogitsLoss()
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [27]:
device

device(type='cuda', index=0)

In [45]:
net = ACCNet(base_net="cifarnet", siamese=True).to(device)

In [37]:
optimizer = torch.optim.Adam(net.parameters(), lr=0.0001)
#optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
#optimizer = torch.optim.SGD(self.net.parameters(), lr=0.0005, momentum=0.9)
#optimizer = torch.optim.SGD(net.parameters(), lr=0.0005, momentum=0.9, weight_decay=5e-4)
print("training...")
print(len(train_dataset))
for epoch in range(150):  # loop over the dataset multiple times
    print(epoch)
    running_loss = 0.0
    step = 0
    for i, data in enumerate(train_loader, 0):
        #print(np.unique(data[2], return_counts=True))
        #print(data[2])
        # get the inputs; data is a list of [inputs, labels]
        x1, x2, labels = data[0].to(device), data[1].to(device), data[2].to(device)
        # zero the parameter gradients
        optimizer.zero_grad()
        # forward + backward + optimize
        outputs = net(x1, x2)
        outputs = outputs.reshape((outputs.shape[0]))
        #labels = labels.reshape((labels.shape[0], 1))
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        # print statistics
        running_loss += loss.item()
        step += 1
    print("loss: ", running_loss/step)
    step = 0
    running_loss = 0.0

training...
9996
0
loss:  0.6843304635076647
1
loss:  0.6386162334403961
2
loss:  0.6231420731244357
3
loss:  0.609805916228529
4
loss:  0.606425242678881
5
loss:  0.5904815750929883
6
loss:  0.5881493030973758
7
loss:  0.5852526525462127
8
loss:  0.5784019082738219
9
loss:  0.5902277527319201
10
loss:  0.5727088638744054
11
loss:  0.5648453886825386
12
loss:  0.5611587092401807
13
loss:  0.5563247169575909
14
loss:  0.5503553915507602
15
loss:  0.5489487216179137
16
loss:  0.5473278331478804
17
loss:  0.5405414676904667
18
loss:  0.5352632664921928
19
loss:  0.5389763195335486
20
loss:  0.530040903226168
21
loss:  0.5308943707497475
22
loss:  0.5199632485035247
23
loss:  0.5205940562799668
24
loss:  0.5190062355824421
25
loss:  0.51568994943145
26
loss:  0.5202168729010462
27
loss:  0.5106102217573942
28
loss:  0.5006278408157948
29
loss:  0.5050624808821825
30
loss:  0.49782417529568135
31
loss:  0.5007734862676031
32
loss:  0.5112086653492094
33
loss:  0.4812195099166937
34
loss:  0

In [38]:
correct = 0
total = 0
# since we're not training, we don't need to calculate the gradients for our outputs
preds = []
with torch.no_grad():
    for data in test_loader:
        x1, x2, labels = data[0].to(device), data[1].to(device), data[2].to(device)
        # calculate outputs by running images through the network
        outputs = net(x1, x2)
        pred = nn.Sigmoid()(outputs)
        #print(pred)
        pred = pred.cpu().numpy()
        pred = pred.reshape(pred.shape[0])
        pred[pred >= 0.5] = 1
        pred[pred < 0.5] = 0
        #print(torch.max(pred.data, 1)[1])
        # the class with the highest energy is what we choose as prediction
        #_, predicted = torch.max(pred.data, 1)
        preds.extend(pred.tolist())


In [39]:
len(preds)

9495

In [40]:
np.unique(preds, return_counts=True)

(array([0., 1.]), array([5090, 4405]))

In [41]:
#preds

In [42]:
y_test_pairs

array([1., 1., 1., ..., 0., 0., 0.])

In [43]:
np.unique(y_test_pairs, return_counts=True)

(array([0., 1.]), array([4500, 4995]))

In [44]:
from sklearn.metrics import classification_report
print(classification_report(y_test_pairs, preds))

              precision    recall  f1-score   support

         0.0       0.64      0.72      0.68      4500
         1.0       0.72      0.63      0.67      4995

    accuracy                           0.68      9495
   macro avg       0.68      0.68      0.68      9495
weighted avg       0.68      0.68      0.68      9495

